data_pipeline:
  target: dev
  outputs:
    dev:
      type: spark
      method: thrift
      schema: warehouse
      host: 192.168.47.51     
      port: 10000
      server_side_parameters:
        "spark.driver.memory": "4g"